### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Osahashi** [spddl/Twitch-Live-Monitor#2]
The add-on doesn't work anymore, I clear the data, disconnect/reconnect my Twitch account and disable/enable it.

The debug log shows a few errors, maybe it helps you find the problem:

Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    send moz-extension://a3903c9b-e5e6-4ad4-b357-159621ea9020/lib/Messages.js:67
Use of nsIFile in content process is deprecated.
Unchecked lastError value: Error: Missing host permission for the tab
Object { OAuth: "XXXX", userID: "43570449", accountnameInput: "Osahashi" }
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist.
    send moz-extension://e09f000c-5fb9-4f6a-82dc-5874b20bbcf2/background.js:2168

**Comment by spddl** [comment]
do you have the same problem with version 0.0.35?

**Comment by Osahashi** [comment]
It works again now, thanks for the fast fix! :)
